default_install_hook_types: [pre-push]

exclude: '^(renv|data)/'

# git push --no-verify skip all hooks
repos:
  - repo: https://github.com/posit-dev/air-pre-commit
    rev: 0.11.0
    hooks:
      - id: air-format

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9030
    hooks:
      - id: lintr